import { DataSource } from 'typeorm';
import {
  Guild,
  Automatic_role,
  Birthday,
  Embed,
  Exempted_role,
  Filtered_word,
  Guild_config,
  Level_config,
  Level_reward,
  Channel_log,
  Log,
  Member,
  Moc_channel,
  Twitch,
  Warning,
} from '@wystrelia/shared';

export const AppDataSource = new DataSource({
  type: 'mysql',
  host: process.env.DB_HOST ?? 'localhost',
  port: Number(process.env.DB_PORT ?? 3306),
  username: process.env.DB_USER,
  password: process.env.DB_PASSWORD,
  database: process.env.DB_NAME,
  entities: [
    Guild,
    Automatic_role,
    Birthday,
    Embed,
    Exempted_role,
    Filtered_word,
    Guild_config,
    Level_config,
    Level_reward,
    Channel_log,
    Log,
    Member,
    Moc_channel,
    Twitch,
    Warning,
  ],
  migrations: [__dirname + '/migrations/*{.ts,.js}'],
  synchronize: true,
});
